### PR TITLE
persistent vloume

### PR DESCRIPTION
**Pull request by Smolder3955**
#1

### CODE REVIEW

**Comment by Trojaner** [comment]
Why did you close it?

**Comment by Smolder3955** [comment]
> Why did you close it?

IMG_20210420_122314_584
Needs to be modified.

**Comment by Trojaner** [comment]
You need to give permission to docker to access the folder you want to mount, thats unrelated to your PR

**Comment by efsg** [comment]
> You need to give permission to docker to access the folder you want to mount, thats unrelated to your PR

image
Ok, I've solved it.

**Pull request merged**
